"""Añadir clave primaria a la tabla Nota

Revision ID: 015876a07a33
Revises: 8b99f223aadd
Create Date: 2025-10-06 15:39:37.603418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015876a07a33'
down_revision = '8b99f223aadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_fisico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_fisico')),
    sa.UniqueConstraint('nombre', name=op.f('uq_plan_fisico_nombre'))
    )
    op.create_table('semana_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('numero_semana', sa.Integer(), nullable=False),
    sa.Column('progreso_pct', sa.Float(), nullable=True),
    sa.Column('dia1_desc', sa.String(length=200), nullable=True),
    sa.Column('dia2_desc', sa.String(length=200), nullable=True),
    sa.Column('sensacion', sa.String(length=200), nullable=True),
    sa.Column('carga_semanal_km', sa.Float(), nullable=True),
    sa.Column('zona_ritmo', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_fisico.id'], name=op.f('fk_semana_plan_plan_id_plan_fisico')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semana_plan'))
    )
    op.create_table('registro_entrenamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('semana_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('dia_entreno', sa.Integer(), nullable=False),
    sa.Column('km_realizados', sa.Float(), nullable=True),
    sa.Column('sensacion_usuario', sa.String(length=200), nullable=True),
    sa.Column('notas_usuario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['semana_id'], ['semana_plan.id'], name=op.f('fk_registro_entrenamiento_semana_id_semana_plan')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_registro_entrenamiento_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registro_entrenamiento'))
    )
    with op.batch_alter_table('nota', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenido', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.alter_column('tema_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_nota_usuario_id_usuario'), 'usuario', ['usuario_id'], ['id'])
        batch_op.drop_column('texto')

    with op.batch_alter_table('pregunta', schema=None) as batch_op:
        batch_op.alter_column('necesita_revision',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('respuesta_correcta_texto',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('imagen_url')
        batch_op.drop_column('dificultad')

    with op.batch_alter_table('respuesta_usuario', schema=None) as batch_op:
        batch_op.alter_column('respuesta_texto_usuario',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('resultado_test', schema=None) as batch_op:
        batch_op.alter_column('tema_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('tema', schema=None) as batch_op:
        batch_op.alter_column('bloque_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('ruta_documento_contexto')
        batch_op.drop_column('tiempo_limite_minutos')
        batch_op.drop_column('pdf_url')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_fisico_actual_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_usuario_plan_fisico_actual_id_plan_fisico'), 'plan_fisico', ['plan_fisico_actual_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_usuario_plan_fisico_actual_id_plan_fisico'), type_='foreignkey')
        batch_op.drop_column('plan_fisico_actual_id')

    with op.batch_alter_table('tema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_url', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('tiempo_limite_minutos', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('ruta_documento_contexto', sa.VARCHAR(length=300), nullable=True))
        batch_op.alter_column('bloque_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('resultado_test', schema=None) as batch_op:
        batch_op.alter_column('tema_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('respuesta_usuario', schema=None) as batch_op:
        batch_op.alter_column('respuesta_texto_usuario',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('pregunta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dificultad', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('imagen_url', sa.VARCHAR(length=300), nullable=True))
        batch_op.alter_column('respuesta_correcta_texto',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('necesita_revision',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('nota', schema=None) as batch_op:
        batch_op.add_column(sa.Column('texto', sa.TEXT(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_nota_usuario_id_usuario'), type_='foreignkey')
        batch_op.alter_column('tema_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('usuario_id')
        batch_op.drop_column('contenido')

    op.drop_table('registro_entrenamiento')
    op.drop_table('semana_plan')
    op.drop_table('plan_fisico')
    # ### end Alembic commands ###
