"""Anadir es_publica a Convocatoria

Revision ID: 0aff06b029c4
Revises: 5b71079926d3
Create Date: 2025-07-07 16:35:35.666907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aff06b029c4'
down_revision = '5b71079926d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convocatoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_publica', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convocatoria', schema=None) as batch_op:
        batch_op.drop_column('es_publica')

    # ### end Alembic commands ###
