"""Añadir campo es_premium a Convocatoria

Revision ID: 0d03e4b45767
Revises: a2775190f654
Create Date: 2025-09-24 12:06:23.191597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d03e4b45767'
down_revision = 'a2775190f654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convocatoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_premium', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convocatoria', schema=None) as batch_op:
        batch_op.drop_column('es_premium')

    # ### end Alembic commands ###
