"""Anadir tabla de acceso con fecha de expiracion

Revision ID: 2435308ff33a
Revises: 
Create Date: 2025-07-06 15:12:43.520029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2435308ff33a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accesos_usuario_convocatoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_expiracion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accesos_usuario_convocatoria', schema=None) as batch_op:
        batch_op.drop_column('fecha_expiracion')

    # ### end Alembic commands ###
