"""Añadir campo de tokens para IA

Revision ID: 2cb258bb54b5
Revises: c1f13423712e
Create Date: 2025-10-02 18:42:19.547877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb258bb54b5'
down_revision = 'c1f13423712e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rag_tokens_restantes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('rag_tokens_restantes')

    # ### end Alembic commands ###
