"""Añadir preferencias de dashboard a Usuario

Revision ID: 35cc2f0c3f3d
Revises: b19166c3c000
Create Date: 2025-09-25 14:13:48.123769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35cc2f0c3f3d'
down_revision = 'b19166c3c000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferencias_dashboard', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('preferencias_dashboard')

    # ### end Alembic commands ###
