"""Añade tabla y relacion para favoritos

Revision ID: 3f488cb7b8c9
Revises: 5f0d6bf0d2e2
Create Date: 2025-06-29 20:07:50.599106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f488cb7b8c9'
down_revision = '5f0d6bf0d2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('pregunta_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pregunta_id'], ['pregunta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'pregunta_id')
    )
    # ### end Alembic commands ###
