"""Añadir columna posicion a Bloque

Revision ID: 507abaed92ae
Revises: 93cdff9189d4
Create Date: 2025-07-07 12:14:32.327001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507abaed92ae'
down_revision = '93cdff9189d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posicion', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloque', schema=None) as batch_op:
        batch_op.drop_column('posicion')

    # ### end Alembic commands ###
