"""Anadir columna de posicion a Bloque

Revision ID: 5b71079926d3
Revises: 507abaed92ae
Create Date: 2025-07-07 13:29:44.174189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b71079926d3'
down_revision = '507abaed92ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloque', schema=None) as batch_op:
        # Añadimos server_default='0' para solucionar el problema de SQLite
        batch_op.add_column(sa.Column('posicion', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloque', schema=None) as batch_op:
        batch_op.drop_column('posicion')

    # ### end Alembic commands ###
