"""Añade funcionalidad de reporte de preguntas

Revision ID: 5f0d6bf0d2e2
Revises: 567b8323474a
Create Date: 2025-06-29 19:13:05.245517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0d6bf0d2e2'
down_revision = '567b8323474a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('respuesta_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('es_correcta', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('respuesta_seleccionada_id', sa.Integer(), nullable=False),
    sa.Column('resultado_test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pregunta_id'], ['pregunta.id'], ),
    sa.ForeignKeyConstraint(['respuesta_seleccionada_id'], ['respuesta.id'], ),
    sa.ForeignKeyConstraint(['resultado_test_id'], ['resultado_test.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuesta_usuario')
    # ### end Alembic commands ###
