"""Creacion inicial de tablas con pdf_url

Revision ID: 6ab3893c86ea
Revises: 
Create Date: 2025-07-10 15:33:30.640814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab3893c86ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_url', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tema', schema=None) as batch_op:
        batch_op.drop_column('pdf_url')

    # ### end Alembic commands ###
