"""Añadir campo contexto_ia a Bloque

Revision ID: 7590e1e37c80
Revises: 0d03e4b45767
Create Date: 2025-09-25 12:08:01.581054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7590e1e37c80'
down_revision = '0d03e4b45767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contexto_ia', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloque', schema=None) as batch_op:
        batch_op.drop_column('contexto_ia')

    # ### end Alembic commands ###
