"""Añadir preferencia de email semanal a Usuario

Revision ID: 92f291d981ae
Revises: a78e517b6584
Create Date: 2025-09-22 10:08:12.108173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f291d981ae'
down_revision = 'a78e517b6584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        # --- LÍNEA MODIFICADA ---
        batch_op.add_column(sa.Column('recibir_resumen_semanal', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('recibir_resumen_semanal')

    # ### end Alembic commands ###