"""Anadir columna de posicion a Tema y Pregunta

Revision ID: 93cdff9189d4
Revises: 2435308ff33a
Create Date: 2025-07-06 17:06:47.932382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93cdff9189d4'
down_revision = '2435308ff33a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pregunta', schema=None) as batch_op:
        # Añadimos server_default='0' para solucionar el problema de SQLite
        batch_op.add_column(sa.Column('posicion', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('tema', schema=None) as batch_op:
        # Añadimos server_default='0' para solucionar el problema de SQLite
        batch_op.add_column(sa.Column('posicion', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tema', schema=None) as batch_op:
        batch_op.drop_column('posicion')

    with op.batch_alter_table('pregunta', schema=None) as batch_op:
        batch_op.drop_column('posicion')

    # ### end Alembic commands ###
