"""Añadir control de acceso IA a Usuario

Revision ID: b19166c3c000
Revises: 7590e1e37c80
Create Date: 2025-09-25 12:47:51.394572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19166c3c000'
down_revision = '7590e1e37c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiene_acceso_ia', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('tiene_acceso_ia')

    # ### end Alembic commands ###
