"""add ruta_documento_contexto to tema

Revision ID: beb46d2ba708
Revises: 35cc2f0c3f3d
Create Date: 2025-09-26 18:27:02.991139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb46d2ba708'
down_revision = '35cc2f0c3f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruta_documento_contexto', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tema', schema=None) as batch_op:
        batch_op.drop_column('ruta_documento_contexto')

    # ### end Alembic commands ###
