"""Migracion inicial

Revision ID: c1f13423712e
Revises: 
Create Date: 2025-10-02 12:00:58.857416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f13423712e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convocatoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('es_publica', sa.Boolean(), nullable=False),
    sa.Column('es_premium', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_convocatoria')),
    sa.UniqueConstraint('nombre', name=op.f('uq_convocatoria_nombre'))
    )
    op.create_table('bloque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=False),
    sa.Column('esta_oculto', sa.Boolean(), nullable=False),
    sa.Column('convocatoria_id', sa.Integer(), nullable=False),
    sa.Column('contexto_ia', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['convocatoria_id'], ['convocatoria.id'], name=op.f('fk_bloque_convocatoria_id_convocatoria')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bloque'))
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=False),
    sa.Column('recibir_resumen_semanal', sa.Boolean(), nullable=False),
    sa.Column('objetivo_principal_id', sa.Integer(), nullable=True),
    sa.Column('ha_visto_tour', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tiene_acceso_ia', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('preferencias_dashboard', sa.JSON(), nullable=True),
    sa.Column('objetivo_fecha', sa.Date(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['objetivo_principal_id'], ['convocatoria.id'], name=op.f('fk_usuario_objetivo_principal_id_convocatoria')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('email', name=op.f('uq_usuario_email'))
    )
    op.create_table('accesos_usuario_convocatoria',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('convocatoria_id', sa.Integer(), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['convocatoria_id'], ['convocatoria.id'], name=op.f('fk_accesos_usuario_convocatoria_convocatoria_id_convocatoria')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_accesos_usuario_convocatoria_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('usuario_id', 'convocatoria_id', name=op.f('pk_accesos_usuario_convocatoria'))
    )
    op.create_table('tema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('bloque_id', sa.Integer(), nullable=True),
    sa.Column('es_simulacro', sa.Boolean(), nullable=False),
    sa.Column('tiempo_limite_minutos', sa.Integer(), nullable=True),
    sa.Column('pdf_url', sa.String(length=300), nullable=True),
    sa.Column('ruta_documento_contexto', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['bloque_id'], ['bloque.id'], name=op.f('fk_tema_bloque_id_bloque')),
    sa.ForeignKeyConstraint(['parent_id'], ['tema.id'], name=op.f('fk_tema_parent_id_tema')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tema'))
    )
    op.create_table('nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tema_id'], ['tema.id'], name=op.f('fk_nota_tema_id_tema')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nota'))
    )
    op.create_table('pregunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=False),
    sa.Column('imagen_url', sa.String(length=300), nullable=True),
    sa.Column('retroalimentacion', sa.Text(), nullable=True),
    sa.Column('dificultad', sa.String(length=50), nullable=False),
    sa.Column('necesita_revision', sa.Boolean(), nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=False),
    sa.Column('tipo_pregunta', sa.String(length=50), nullable=False),
    sa.Column('respuesta_correcta_texto', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['tema_id'], ['tema.id'], name=op.f('fk_pregunta_tema_id_tema')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pregunta'))
    )
    op.create_table('resultado_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tema_id'], ['tema.id'], name=op.f('fk_resultado_test_tema_id_tema')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_resultado_test_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resultado_test'))
    )
    op.create_table('favoritos',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pregunta_id'], ['pregunta.id'], name=op.f('fk_favoritos_pregunta_id_pregunta')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_favoritos_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('usuario_id', 'pregunta_id', name=op.f('pk_favoritos'))
    )
    op.create_table('respuesta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('es_correcta', sa.Boolean(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pregunta_id'], ['pregunta.id'], name=op.f('fk_respuesta_pregunta_id_pregunta')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_respuesta'))
    )
    op.create_table('respuesta_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('es_correcta', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('respuesta_seleccionada_id', sa.Integer(), nullable=True),
    sa.Column('respuesta_texto_usuario', sa.String(length=500), nullable=True),
    sa.Column('resultado_test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pregunta_id'], ['pregunta.id'], name=op.f('fk_respuesta_usuario_pregunta_id_pregunta')),
    sa.ForeignKeyConstraint(['respuesta_seleccionada_id'], ['respuesta.id'], name=op.f('fk_respuesta_usuario_respuesta_seleccionada_id_respuesta')),
    sa.ForeignKeyConstraint(['resultado_test_id'], ['resultado_test.id'], name=op.f('fk_respuesta_usuario_resultado_test_id_resultado_test')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_respuesta_usuario_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_respuesta_usuario'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuesta_usuario')
    op.drop_table('respuesta')
    op.drop_table('favoritos')
    op.drop_table('resultado_test')
    op.drop_table('pregunta')
    op.drop_table('nota')
    op.drop_table('tema')
    op.drop_table('accesos_usuario_convocatoria')
    op.drop_table('usuario')
    op.drop_table('bloque')
    op.drop_table('convocatoria')
    # ### end Alembic commands ###
