"""Añade fecha_creacion a Usuario

Revision ID: d8a0c1af2552
Revises: f029326a19db
Create Date: 2025-10-01 13:43:50.930361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a0c1af2552'
down_revision = 'f029326a19db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objetivo_fecha', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('objetivo_fecha')

    # ### end Alembic commands ###
