"""Añadir objetivo y flag de tour a Usuario

Revision ID: e032fe0ea174
Revises: f4b9159037f7
Create Date: 2025-09-23 18:43:09.840373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e032fe0ea174'
down_revision = 'f4b9159037f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convocatoria', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_convocatoria_nombre'), ['nombre'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ha_visto_tour', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_usuario_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_usuario_email'), type_='unique')
        batch_op.drop_column('ha_visto_tour')

    with op.batch_alter_table('convocatoria', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_convocatoria_nombre'), type_='unique')

    # ### end Alembic commands ###
