"""Add fecha_inicio_plan to Usuario

Revision ID: e2443145e995
Revises: 95d43c548086
Create Date: 2025-10-10 14:35:49.388782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2443145e995'
down_revision = '95d43c548086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiempo_limite_minutos', sa.Integer(), nullable=True))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_inicio_plan', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('fecha_inicio_plan')

    with op.batch_alter_table('tema', schema=None) as batch_op:
        batch_op.drop_column('tiempo_limite_minutos')

    # ### end Alembic commands ###
