"""Añade fecha de objetivo a Usuario

Revision ID: f029326a19db
Revises: beb46d2ba708
Create Date: 2025-09-27 11:43:12.300442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f029326a19db'
down_revision = 'beb46d2ba708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objetivo_fecha', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('objetivo_fecha')

    # ### end Alembic commands ###
