"""Añadir objetivo principal a Usuario

Revision ID: f4b9159037f7
Revises: 92f291d981ae
Create Date: 2025-09-23 18:19:20.791544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b9159037f7'
down_revision = '92f291d981ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objetivo_principal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'convocatoria', ['objetivo_principal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('objetivo_principal_id')

    # ### end Alembic commands ###
